[build]
  publish = "_site"
  command = "./build.sh"
  functions = "functions"

[build.environment]
  GO_VERSION = "1.20.2"
  HUGO_VERSION = "0.111.2"

[[redirects]]
  from = "/security.html"
  to = "/security/"
  status = 301

[[redirects]]
  from = "https://syncthing.org/"
  to = "https://syncthing.net/foundation/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.syncthing.org/"
  to = "https://syncthing.net/foundation/"
  status = 301
  force = true

[[redirects]]
  from = "https://syncthing.org/*"
  to = "https://syncthing.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.syncthing.org/*"
  to = "https://syncthing.net/:splat"
  status = 301
  force = true
